modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/gigaherz/ElementsOfPower/issues"

[[mods]] #mandatory
modId="elementsofpower" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Elements of Power" #mandatory
updateJSONURL="https://raw.githubusercontent.com/gigaherz/ElementsOfPower/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/elements-of-power" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
A magic mod about the raw power elemental essences
'''

[[dependencies.elementsofpower]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.68,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.elementsofpower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
